// The blog's articles. Each article has:
//   slug      the address (/blog/<slug>), in English letters
//   category  one of BLOG_CATEGORIES in blog.js
//   date      publish date (Israel time); until then the article is not on the site
//   keyword   the one search phrase this article targets, in each language. It must not be the
//             main phrase of any page of the site (see the SEO keyword map) or of another article.
//   image     the illustration at the top of the article
//   links     the site pages the article sends readers to (the pages that own the broader phrase)
//   he / en   title, description (for search results, up to about 155 characters) and body
//
// Body blocks: ["p", text], ["h2", text], ["ul", [items]], ["ol", [items]], ["tip", text].
// Inside text, [words](/path) is a link to a page of the site.
export const BLOG_POSTS = [
  {
    slug: "how-to-write-a-social-story",
    category: "social-stories",
    date: "2026-09-28",
    keyword: { he: "איך כותבים סיפור חברתי", en: "how to write a social story" },
    image: "/icon-bank/navigation-v2/social-stories-flat.webp",
    links: ["/parent/social-stories"],
    he: {
      title: "איך כותבים סיפור חברתי לילד – מדריך בשלבים",
      description: "איך כותבים סיפור חברתי שילד באמת מבין: בחירת מצב אחד, משפטים שמתארים ולא מטיפים, תמונות, ומתי לקרוא. מדריך קצר של מרפאה בעיסוק.",
      body: [
        ["p", "ילד שיודע מה עומד לקרות מרגיש בטוח יותר. זה כל הרעיון מאחורי סיפור חברתי: סיפור קצר ומאויר שמתאר לילד מצב מסוים – הליכה לרופא, יום ראשון בגן, אורחים בבית – מה קורה בו, מה אנשים מרגישים, ומה הוא יכול לעשות. הסיפורים החברתיים פותחו במקור עבור ילדים על הרצף האוטיסטי, אבל הם עוזרים לכל ילד שמתקשה עם שינוי, המתנה או מצב חדש."],
        ["h2", "שלב 1: בוחרים מצב אחד בלבד"],
        ["p", "סיפור טוב עוסק במצב אחד, ממוקד וקונקרטי. לא „איך מתנהגים יפה”, אלא „מה קורה כשסבתא באה לבקר” או „מה עושים כשמפסידים במשחק”. כדאי להתחיל ממצב שחוזר על עצמו ושגורם לקושי, כי שם הסיפור יעזור הכי מהר."],
        ["h2", "שלב 2: מסתכלים על המצב דרך העיניים של הילד"],
        ["p", "לפני שכותבים, שואלים: מה הילד רואה, שומע ומרגיש במצב הזה? מה מפחיד אותו או מבלבל אותו? ילד שבוכה במספרה אולי לא פוחד מהתספורת, אלא מהרעש של המכונה או מהשערות שנדבקות לצוואר. כשמבינים מה באמת קשה, יודעים מה לכתוב."],
        ["h2", "שלב 3: כותבים משפטים שמתארים, ומעט משפטים שמכוונים"],
        ["p", "רוב המשפטים בסיפור צריכים לתאר: מה קורה, מי נמצא שם ומה אנשים מרגישים. רק מעט משפטים מציעים לילד מה לעשות. כלל אצבע טוב: לפחות שני משפטים שמתארים על כל משפט שמכוון."],
        ["ul", [
          "משפט שמתאר: „במספרה יש מכונה שעושה רעש כמו זמזום.”",
          "משפט שמתאר רגש: „לפעמים הרעש מרגיש חזק מדי.”",
          "משפט שמכוון: „אני יכול לבקש לשים אוזניות.”",
        ]],
        ["p", "כותבים בגוף ראשון („אני”), בזמן הווה ובשפה חיובית. במקום „אסור לצעוק” כותבים „אני יכול לדבר בקול שקט”. כדאי להשאיר מקום לגמישות: „בדרך כלל”, „לפעמים”, כדי שהסיפור יישאר נכון גם כשמשהו משתנה."],
        ["h2", "שלב 4: משפט אחד בכל עמוד, עם תמונה"],
        ["p", "לילדים צעירים עדיף עמוד אחד לכל רעיון, עם תמונה ברורה ומשפט אחד או שניים. התמונה צריכה להראות בדיוק את מה שכתוב, בלי פרטים שמסיחים את הדעת. ב[מחולל הסיפורים החברתיים](/parent/social-stories) באתר אפשר לבחור סיפור מוכן, לשים בו את הדמות של הילד ולהדפיס."],
        ["h2", "שלב 5: קוראים יחד, בזמן רגוע"],
        ["p", "את הסיפור קוראים לפני המצב – לא בתוכו, וממש לא אחרי התפרצות. הזמן הכי טוב הוא רגע רגוע: לפני השינה, או בבוקר של היום שבו המצב יקרה. קוראים כמה ימים ברציפות, ומאפשרים לילד לדפדף לבד. אחרי שהמצב עבר, אפשר לקרוא שוב ולדבר על מה שהיה."],
        ["tip", "טיפ מהקליניקה: כשהסיפור מצליח, לא ממהרים להעלים אותו. משאירים אותו זמין, והילד יחזור אליו בעצמו כשירגיש צורך."],
        ["h2", "מתי לפנות לעזרה"],
        ["p", "אם הקושי במצבים מסוימים חוזר שוב ושוב, פוגע בתפקוד היומיומי של הילד או של המשפחה, או מלווה בהתפרצויות חזקות, כדאי להתייעץ עם מרפאה בעיסוק או עם איש מקצוע אחר שמכיר את הילד. סיפור חברתי הוא כלי מצוין, אבל הוא עובד הכי טוב כחלק מתוכנית שמתאימה לילד."],
      ],
    },
    en: {
      title: "How to Write a Social Story for Your Child: A Step-by-Step Guide",
      description: "How to write a social story your child really understands: one situation, sentences that describe rather than lecture, pictures, and when to read it.",
      body: [
        ["p", "Children feel safer when they know what is going to happen. That is the whole idea behind a social story: a short, illustrated story that describes one situation for a child – a doctor's visit, the first day of preschool, guests at home – what happens, how people feel, and what the child can do. Social stories were first developed for autistic children, but they help any child who struggles with change, waiting, or new situations."],
        ["h2", "Step 1: Choose one situation"],
        ["p", "A good story is about one focused, concrete situation. Not \"how to behave nicely\", but \"what happens when Grandma visits\" or \"what to do when I lose a game\". Start with a situation that keeps coming back and keeps being hard – that is where a story helps fastest."],
        ["h2", "Step 2: See the situation through your child's eyes"],
        ["p", "Before writing, ask: what does my child see, hear and feel in this situation? What scares or confuses them? A child who cries at the barber may not be afraid of the haircut at all, but of the clipper's noise or the hair on their neck. Once you know what is really hard, you know what to write."],
        ["h2", "Step 3: Mostly describing sentences, a few guiding ones"],
        ["p", "Most sentences should describe: what happens, who is there, and how people feel. Only a few should suggest what to do. A good rule of thumb: at least two describing sentences for every guiding sentence."],
        ["ul", [
          "Describing: \"At the barber there is a machine that buzzes.\"",
          "Describing a feeling: \"Sometimes the noise feels too loud.\"",
          "Guiding: \"I can ask to wear my headphones.\"",
        ]],
        ["p", "Write in the first person (\"I\"), in the present tense, and in positive language. Instead of \"No shouting\", write \"I can use a quiet voice\". Leave room for change with words like \"usually\" and \"sometimes\", so the story stays true when something is different."],
        ["h2", "Step 4: One sentence per page, with a picture"],
        ["p", "For young children, one idea per page works best, with a clear picture and one or two sentences. The picture should show exactly what the text says, with nothing distracting. In the site's [social story builder](/parent/social-stories) you can choose a ready story, put your child's character in it, and print it."],
        ["h2", "Step 5: Read it together at a calm time"],
        ["p", "Read the story before the situation – not during it, and never right after a meltdown. The best time is a calm moment: at bedtime, or on the morning of the day it will happen. Read it several days in a row and let your child turn the pages. Afterwards, read it again and talk about how it went."],
        ["tip", "A tip from the clinic: when a story works, don't rush to put it away. Keep it within reach, and your child will come back to it when they need it."],
        ["h2", "When to ask for help"],
        ["p", "If certain situations are hard again and again, affect your child's or your family's daily life, or come with strong meltdowns, talk with an occupational therapist or another professional who knows your child. A social story is a great tool, and it works best as part of a plan made for your child."],
      ],
    },
  },
  {
    slug: "signs-of-fine-motor-difficulties",
    category: "fine-motor",
    date: "2026-10-01",
    keyword: { he: "סימנים לקושי במוטוריקה עדינה", en: "signs of fine motor delay" },
    image: "/icon-bank/search/pencil-grip.webp",
    links: ["/parent/all"],
    he: {
      title: "סימנים לקושי במוטוריקה עדינה אצל ילדים – מתי לשים לב",
      description: "אילו סימנים מרמזים על קושי במוטוריקה עדינה: אחיזת עיפרון, גזירה, כפתורים ואכילה עצמאית. מה בודקים בבית ומתי כדאי לפנות למרפאה בעיסוק.",
      body: [
        ["p", "מוטוריקה עדינה היא היכולת להשתמש בשרירים הקטנים של הידיים והאצבעות: לאחוז עיפרון, לגזור, לסגור כפתור, להבריג מכסה ולאכול עם מזלג. ילדים מתפתחים בקצב שונה, ולכן קושי נקודתי הוא לא סיבה לדאגה. מה שכדאי לחפש הוא דפוס: קושי שחוזר בכמה תחומים, או שמפריע לילד בחיי היום־יום."],
        ["h2", "סימנים שכדאי לשים לב אליהם"],
        ["ul", [
          "אחיזת עיפרון באגרוף סגור גם אחרי גיל 4 וחצי–5, או החלפה של יד הכתיבה כל הזמן.",
          "ציור וכתיבה בלחץ חזק מאוד (העיפרון נשבר, הדף נקרע) או חלש מאוד (קו כמעט לא נראה).",
          "קושי בגזירה בגיל הגן: המספריים נסגרים ונפתחים בלי לחתוך, או שהיד שמחזיקה את הדף לא עוזרת.",
          "הימנעות מפעילויות כמו פאזלים, לגו, השחלה או צביעה, והעדפה עקבית של משחק תנועתי בלבד.",
          "קושי בלבוש ובאכילה ביחס לבני הגיל: כפתורים, רוכסן, שימוש במזלג ובכפית.",
          "עייפות מהירה של היד, או תלונות שכואב לכתוב.",
        ]],
        ["h2", "למה זה קורה?"],
        ["p", "לפעמים הסיבה היא פשוט מעט התנסות: ילד שמשחק בעיקר במסכים או בחוץ עדיין לא תרגל את הידיים. לפעמים הקושי קשור לחוזק של הכתפיים ושל כף היד, לתחושה באצבעות, לתיאום בין שתי הידיים או לתכנון תנועה. מוטוריקה עדינה נשענת על בסיס יציב: ילד שקשה לו לשבת יציב או לשמור על כתף חזקה, יתקשה גם עם העיפרון."],
        ["h2", "מה אפשר לעשות בבית"],
        ["p", "הדרך הטובה ביותר לחזק את הידיים היא דרך משחק, בלי להפוך אותו לשיעורי בית. כמה רעיונות מהאתר:"],
        ["ul", [
          "[העברת פומפונים עם פינצטה](/activity/seed-37) – מחזקת את אחיזת הצבת בין האגודל לאצבע.",
          "[אטבים לפי הצבע](/activity/seed-72) – לחיצה על אטב מחזקת את האצבעות ומלמדת לכוון כוח.",
          "[מדורה מפלסטלינה](/activity/seed-63) – גלגול, לישה ומעיכה מחממים את היד לפני כתיבה.",
          "עבודה על משטח אנכי – ציור על דף שמודבק לקיר או על חלון מחזקת את הכתף ומיישרת את שורש כף היד.",
        ]],
        ["tip", "טיפ מהקליניקה: עפרונות קצרים ופנדות קטנות מזמינים אחיזה נכונה יותר מעפרון ארוך. נסו לשבור עפרון צבעוני לשניים."],
        ["h2", "מתי כדאי לפנות להערכה"],
        ["p", "אם כמה מהסימנים מופיעים יחד, אם הקושי לא משתפר עם תרגול, או אם הילד מתחיל להימנע ולהגיד „אני לא יודע לצייר”, כדאי לפנות להערכה של מרפאה בעיסוק. הערכה מוקדמת עוזרת להבין מה עומד מאחורי הקושי ולבנות תוכנית שמתאימה בדיוק לילד. ב[מאגר הפעילויות](/parent/all) אפשר לסנן פעילויות לפי גיל ולפי תחום."],
      ],
    },
    en: {
      title: "Signs of Fine Motor Difficulties in Children: What to Look For",
      description: "Which signs suggest fine motor difficulties: pencil grasp, cutting, buttons and self-feeding. What to try at home and when to see an occupational therapist.",
      body: [
        ["p", "Fine motor skills are the ability to use the small muscles of the hands and fingers: holding a pencil, cutting, buttoning, twisting a lid and eating with a fork. Children develop at different paces, so one hard skill is not a reason to worry. What to look for is a pattern: difficulty that shows up in several areas, or that gets in the way of your child's daily life."],
        ["h2", "Signs worth noticing"],
        ["ul", [
          "Holding the pencil in a closed fist after age 4½–5, or switching hands all the time.",
          "Drawing and writing with very hard pressure (the pencil breaks, the paper tears) or very light pressure (the line is barely visible).",
          "Difficulty cutting in preschool: the scissors open and close without cutting, or the helper hand does not hold the paper.",
          "Avoiding puzzles, building blocks, stringing beads or coloring, and always preferring only active play.",
          "Difficulty dressing and eating compared with peers: buttons, zippers, using a fork and spoon.",
          "A hand that tires quickly, or complaints that writing hurts.",
        ]],
        ["h2", "Why does it happen?"],
        ["p", "Sometimes it is simply little practice: a child who plays mostly on screens or outdoors has not trained their hands yet. Sometimes it is about shoulder and hand strength, the feeling in the fingers, coordination between the two hands, or motor planning. Fine motor skills rest on a stable base: a child who finds it hard to sit steadily or keep a strong shoulder will also struggle with a pencil."],
        ["h2", "What you can do at home"],
        ["p", "The best way to strengthen the hands is through play, without turning it into homework. A few ideas from the site:"],
        ["ul", [
          "[Moving pom-poms with tweezers](/activity/seed-37) – strengthens the pincer grasp between thumb and finger.",
          "[Clothespins by color](/activity/seed-72) – squeezing a clothespin strengthens the fingers and teaches how much force to use.",
          "[A play-dough campfire](/activity/seed-63) – rolling, kneading and squashing warm up the hand before writing.",
          "Working on a vertical surface – drawing on paper taped to a wall or window strengthens the shoulder and straightens the wrist.",
        ]],
        ["tip", "A tip from the clinic: short pencils and small crayons invite a better grasp than long ones. Try breaking a colored pencil in half."],
        ["h2", "When to ask for an evaluation"],
        ["p", "If several signs appear together, if the difficulty does not improve with practice, or if your child starts avoiding and saying \"I can't draw\", ask an occupational therapist for an evaluation. An early evaluation helps you understand what is behind the difficulty and build a plan that fits your child. In the [activity library](/parent/all) you can filter activities by age and skill."],
      ],
    },
  },
  {
    slug: "morning-routine-tips-for-kids",
    category: "routine",
    date: "2026-10-04",
    keyword: { he: "טיפים להתארגנות בוקר עם ילדים", en: "morning routine tips for kids" },
    image: "/icon-bank/navigation-v2/morning-routine-flat.webp",
    links: ["/parent/morning-routine"],
    he: {
      title: "בוקר בלי צעקות: 7 טיפים להתארגנות בוקר עם ילדים",
      description: "7 טיפים מעשיים של מרפאה בעיסוק לבוקר רגוע יותר עם ילדים: הכנה מהערב, סדר קבוע, לוח חזותי, זמן מספיק ועצמאות בצעדים קטנים.",
      body: [
        ["p", "הבקרים הם אחד הזמנים הכי עמוסים בבית: כולם ממהרים, הילד עוד לא התעורר, והנעל השנייה נעלמה. החדשות הטובות: רוב הריבים בבוקר לא נובעים מחוסר רצון של הילד, אלא מכך שיש יותר מדי החלטות, יותר מדי מילים ומעט מדי זמן. הנה שבעה דברים שעובדים גם בבתים עמוסים."],
        ["h2", "1. מתחילים מהערב"],
        ["p", "בוחרים בגדים, מכינים תיק ומניחים נעליים ליד הדלת עוד בערב. כל החלטה שעוברת לערב היא ויכוח אחד פחות בבוקר."],
        ["h2", "2. אותו סדר, כל יום"],
        ["p", "כשהסדר קבוע – קמים, שירותים, מתלבשים, אוכלים, מצחצחים שיניים, נועלים נעליים – הילד לא צריך לחשוב מה בא עכשיו. הגוף לומד את הרצף, והבוקר נעשה אוטומטי יותר."],
        ["h2", "3. מראים במקום להגיד"],
        ["p", "ילדים רבים מתקשים לזכור רשימה של הוראות מילוליות, בטח בבוקר. לוח חזותי עם תמונה לכל שלב מאפשר לילד לבדוק לבד מה הלאה. ב[לוח התארגנות בוקר](/parent/morning-routine) באתר אפשר לבנות לוח עם השלבים שלכם, בסדר שלכם, ולהדפיס אותו."],
        ["h2", "4. פחות מילים, יותר הפניה"],
        ["p", "במקום „כמה פעמים אמרתי לך להתלבש?” אפשר פשוט לשאול „מה הדבר הבא בלוח?”. ההפניה ללוח מורידה את המתח מהשיחה ונותנת לילד תחושה שהוא מנהל את הבוקר."],
        ["h2", "5. נותנים זמן אמיתי"],
        ["p", "אם הבוקר תמיד לחוץ, כנראה שהוא קצר מדי. עשר דקות נוספות יכולות להפוך בוקר של צעקות לבוקר רגוע. ילדים שמתעוררים לאט או שזקוקים ל„זמן התחממות” צריכים את המרווח הזה במיוחד."],
        ["h2", "6. עצמאות בצעדים קטנים"],
        ["p", "לא צריך לבקש מהילד לעשות הכול לבד בבת אחת. מתחילים משלב אחד שהוא עושה לבד לגמרי – למשל לנעול נעליים – ומוסיפים שלב כשזה מצליח. בגדים נוחים (מכנסיים עם גומי, נעלי סקוץ') מקלים מאוד."],
        ["h2", "7. מסיימים בהצלחה"],
        ["p", "כשכל השלבים הושלמו, כדאי לסמן את זה: מדבקה, „כיף!” או דקה של משחק יחד לפני היציאה. ילד שמסיים את הבוקר בתחושת הצלחה מגיע רגוע יותר לגן ולבית הספר."],
        ["tip", "טיפ מהקליניקה: אם יש שלב אחד שתמיד נתקע (בדרך כלל ההתלבשות), שווה לבדוק למה. לפעמים זו תחושה של בד או תווית שמציקה, ולא „עקשנות”."],
      ],
    },
    en: {
      title: "Mornings Without Yelling: 7 Morning Routine Tips for Kids",
      description: "Seven tips from an occupational therapist for calmer mornings with kids: prep the night before, a fixed order, a visual board and step-by-step independence.",
      body: [
        ["p", "Mornings are one of the busiest times at home: everyone is rushing, your child is not awake yet, and the second shoe has vanished. The good news: most morning fights are not about a child who won't cooperate, but about too many decisions, too many words and too little time. Here are seven things that work even in busy homes."],
        ["h2", "1. Start the night before"],
        ["p", "Choose clothes, pack the backpack, and put shoes by the door in the evening. Every decision you move to the evening is one fewer argument in the morning."],
        ["h2", "2. The same order, every day"],
        ["p", "When the order is fixed – get up, bathroom, get dressed, eat, brush teeth, shoes on – your child does not have to think about what comes next. The body learns the sequence, and the morning becomes more automatic."],
        ["h2", "3. Show instead of telling"],
        ["p", "Many children struggle to remember a list of spoken instructions, especially in the morning. A visual board with a picture for each step lets your child check what is next on their own. With the site's [morning routine board](/parent/morning-routine) you can build a board with your steps, in your order, and print it."],
        ["h2", "4. Fewer words, more pointing"],
        ["p", "Instead of \"How many times have I told you to get dressed?\" simply ask \"What's next on the board?\". Pointing to the board takes the tension out of the conversation and lets your child feel in charge of the morning."],
        ["h2", "5. Allow real time"],
        ["p", "If the morning is always rushed, it is probably too short. Ten more minutes can turn a morning of yelling into a calm one. Children who wake up slowly or need \"warm-up time\" especially need this room."],
        ["h2", "6. Independence in small steps"],
        ["p", "You don't need to ask your child to do everything alone at once. Start with one step they do completely on their own – for example putting on shoes – and add a step once it works. Easy clothes (elastic waists, Velcro shoes) help a lot."],
        ["h2", "7. End on a success"],
        ["p", "When all the steps are done, mark it: a sticker, a cheer, or a minute of play together before leaving. A child who ends the morning feeling successful arrives calmer at preschool or school."],
        ["tip", "A tip from the clinic: if one step always gets stuck (usually dressing), find out why. Sometimes it's the feel of a fabric or an itchy label, not \"stubbornness\"."],
      ],
    },
  },
  {
    slug: "calm-down-corner-at-home",
    category: "sensory",
    date: "2026-10-07",
    keyword: { he: "פינת הרגעה לילד", en: "how to make a calm down corner" },
    image: "/icon-bank/emotions/calm.webp",
    links: ["/parent/all", "/parent/social-stories"],
    he: {
      title: "איך בונים פינת הרגעה לילד בבית",
      description: "פינת הרגעה היא מקום קטן שבו ילד לומד להירגע: מה שמים בה, איפה ממקמים אותה, איך מלמדים להשתמש בה ומה חשוב שלא יקרה בה.",
      body: [
        ["p", "פינת הרגעה היא מקום קטן ושקט בבית שאליו הילד יכול ללכת כשהוא מרגיש שהכול „יותר מדי”: כעס, תסכול, עייפות או רעש. המטרה היא לא להעניש ולא להרחיק, אלא ללמד את הילד לזהות שהוא צריך הפסקה, ולתת לו כלים להירגע – קודם עם מבוגר לידו, ובהדרגה גם לבד."],
        ["h2", "איפה ממקמים את הפינה?"],
        ["p", "בחרו מקום קבוע, רחוק מהטלוויזיה ומהמעבר של כולם, אבל לא מבודד – הילד צריך להרגיש שאתם קרובים. פינה בחדר הילדים, מאחורי הספה או אוהל קטן בסלון עובדים מצוין. תאורה רכה ומעט גירויים על הקירות עוזרים לגוף להאט."],
        ["h2", "מה שמים בפינה?"],
        ["ul", [
          "משהו רך לשבת או לשכב עליו: כרית גדולה, פוף או שמיכה כבדה.",
          "משהו ללחוץ ולמעוך: כדור ספוג, פלסטלינה או כרית קטנה.",
          "משהו להסתכל עליו: בקבוק חושי שהחול בו שוקע לאט. אפשר להכין אחד יחד לפי [הכנת בקבוק חול צבעוני](/activity/seed-1).",
          "אוזניות שמפחיתות רעש לילדים שרגישים לקולות.",
          "כרטיסיות רגשות עם פרצופים, כדי לעזור לילד להגיד מה הוא מרגיש.",
          "ספר אהוב או סיפור חברתי על מה עושים כשכועסים.",
        ]],
        ["h2", "מלמדים את הפינה כשרגוע"],
        ["p", "הטעות הנפוצה היא להציג את הפינה לראשונה בדיוק ברגע של התפרצות. עדיף לבנות אותה יחד עם הילד, לתת לו לבחור מה ייכנס אליה, ולתרגל בה ברגעים טובים: לשבת, לנשום לאט, ללחוץ על הכדור. כך, כשיגיע רגע קשה, הפינה תהיה מקום מוכר ונעים. [סיפור חברתי](/parent/social-stories) קצר על הפינה עוזר מאוד לילדים צעירים."],
        ["h2", "מה חשוב שלא יקרה בפינה"],
        ["p", "הפינה היא לא „עונש” ולא „לך לחדר שלך”. לא שולחים אליה בכעס, ולא מגבילים זמן. מזמינים: „נראה שקשה לך. רוצה שנלך לפינה הרגועה?”. ילדים צעירים צריכים מבוגר לידם בפינה, ורק עם הזמן לומדים להשתמש בה לבד."],
        ["tip", "טיפ מהקליניקה: נשימה של „להריח פרח ולכבות נר” – שאיפה דרך האף ונשיפה ארוכה דרך הפה – היא דרך פשוטה ללמד ילד להאט את הגוף. תרגלו אותה יחד כשכולם רגועים."],
      ],
    },
    en: {
      title: "How to Make a Calm Down Corner at Home",
      description: "A calm down corner is a small space where a child learns to calm down: what to put in it, where to place it, how to teach it and what should never happen there.",
      body: [
        ["p", "A calm down corner is a small, quiet spot at home your child can go to when everything feels \"too much\": anger, frustration, tiredness or noise. The goal is not to punish or send away, but to teach your child to notice when they need a break, and to give them tools to calm down – first with an adult nearby, and gradually on their own."],
        ["h2", "Where should it be?"],
        ["p", "Choose a fixed spot, away from the TV and the busy parts of the home, but not isolated – your child should feel you are close. A corner of the bedroom, the space behind the sofa or a small tent in the living room all work well. Soft light and little on the walls help the body slow down."],
        ["h2", "What goes in the corner?"],
        ["ul", [
          "Something soft to sit or lie on: a big cushion, a beanbag or a weighted blanket.",
          "Something to squeeze: a foam ball, play dough or a small pillow.",
          "Something to watch: a sensory bottle where sand sinks slowly. You can make one together with [the colorful sand bottle](/activity/seed-1).",
          "Noise-reducing headphones for children who are sensitive to sounds.",
          "Feelings cards with faces, to help your child say what they feel.",
          "A favorite book, or a social story about what to do when angry.",
        ]],
        ["h2", "Teach the corner when calm"],
        ["p", "A common mistake is introducing the corner for the first time right in the middle of a meltdown. It is better to build it together with your child, let them choose what goes in, and practice there at good moments: sitting, breathing slowly, squeezing the ball. Then, when a hard moment comes, the corner is a familiar and pleasant place. A short [social story](/parent/social-stories) about the corner helps young children a lot."],
        ["h2", "What should never happen there"],
        ["p", "The corner is not a punishment and not \"go to your room\". Don't send your child there in anger, and don't set a time limit. Invite instead: \"It looks hard for you. Want to go to the calm corner together?\". Young children need an adult with them in the corner, and only with time learn to use it on their own."],
        ["tip", "A tip from the clinic: \"smell the flower, blow out the candle\" – breathing in through the nose and a long breath out through the mouth – is a simple way to teach a child to slow their body down. Practice it together when everyone is calm."],
      ],
    },
  },
  {
    slug: "benefits-of-cooking-with-kids",
    category: "kitchen-science",
    date: "2026-10-10",
    keyword: { he: "בישול עם ילדים", en: "benefits of cooking with kids" },
    image: "/icon-bank/navigation-v2/recipes-flat.webp",
    links: ["/parent/recipes", "/parent/experiments"],
    he: {
      title: "למה כדאי לבשל עם ילדים: מה מתפתח במטבח",
      description: "בישול עם ילדים מפתח מוטוריקה עדינה, תכנון, שפה, חשבון והתנסות חושית במזון. מה כל גיל יכול לעשות ואיך מתחילים בלי בלגן מיותר.",
      body: [
        ["p", "מבחינת מרפאה בעיסוק, המטבח הוא אחד מחדרי הטיפול הטובים בבית. יש בו משימה אמיתית עם מטרה ברורה, שלבים שצריך לעשות לפי סדר, והרבה עבודה לידיים ולחושים. וכשמסיימים, יש גם משהו טעים לאכול. הנה מה שמתפתח כשמבשלים יחד."],
        ["h2", "הידיים עובדות"],
        ["p", "ערבוב בכף מחזק את הכתף ואת פרק היד. מריחה בסכין שולחן, קילוף ביצה או תפוז ופיזור סוכריות באצבעות מתרגלים מוטוריקה עדינה ותיאום בין שתי הידיים – יד אחת מחזיקה, השנייה עובדת. אלה בדיוק המיומנויות שהילד צריך אחר כך לגזירה ולכתיבה."],
        ["h2", "הראש מתכנן"],
        ["p", "מתכון הוא רצף: קודם מכינים את המצרכים, אחר כך מערבבים, אחר כך אופים. ילד שעוקב אחרי מתכון מתרגל תכנון, זיכרון עבודה והמתנה – „עכשיו מחכים עשר דקות לתנור”. [מתכונים מאוירים](/parent/recipes) עם תמונה לכל שלב מאפשרים גם לילד שעוד לא קורא לעקוב לבד."],
        ["h2", "שפה וחשבון בלי שמרגישים"],
        ["p", "„שתי כפות”, „חצי כוס”, „עוד אחת”, „יותר” ו„פחות” – המטבח מלא במושגים של כמות וגודל. גם המילים מתרחבות: לקצוץ, לערבב, להקציף, רך, דביק, פריך."],
        ["h2", "הכרות עם מזון חדש"],
        ["p", "ילדים בררנים באוכל טועמים הרבה יותר בקלות משהו שהכינו בעצמם. גם רק לגעת, להריח ולערבב מזון חדש – בלי לחייב לטעום – היא התקדמות. הבישול מאפשר להכיר מרקמים וריחות בקצב של הילד."],
        ["h2", "מה כל גיל יכול לעשות"],
        ["ul", [
          "גיל 2–3: לשטוף ירקות, לשפוך מצרכים שנמדדו מראש, לערבב, לפזר.",
          "גיל 4–5: למרוח, לחתוך דברים רכים בסכין שולחן, לשבור ביצה לקערה, לסדר על מגש.",
          "גיל 6 ומעלה: למדוד לבד, לקלף בקולפן, לקרוא מתכון פשוט, לחתוך בהשגחה צמודה.",
        ]],
        ["tip", "טיפ מהקליניקה: מכינים הכול מראש על מגש אחד, ומשאירים לילד את החלקים שהוא יכול להצליח בהם. תחושת „אני הכנתי” שווה יותר ממתכון מושלם."],
        ["p", "ואם אתם רוצים להמשיך את הסקרנות מהמטבח, [הניסויים לילדים](/parent/experiments) באתר משתמשים בהרבה מאותם חומרים שיש לכם כבר בארון."],
      ],
    },
    en: {
      title: "The Benefits of Cooking With Kids: What Develops in the Kitchen",
      description: "Cooking with kids builds fine motor skills, planning, language, math and sensory experience with food. What each age can do, and how to start without extra mess.",
      body: [
        ["p", "For an occupational therapist, the kitchen is one of the best therapy rooms at home. It offers a real task with a clear goal, steps that must be done in order, and plenty of work for the hands and senses. And at the end, there is something tasty to eat. Here is what develops when you cook together."],
        ["h2", "The hands get to work"],
        ["p", "Stirring with a spoon strengthens the shoulder and wrist. Spreading with a table knife, peeling an egg or an orange and sprinkling with the fingers practice fine motor skills and two-handed coordination – one hand holds, the other works. These are exactly the skills a child needs later for cutting and writing."],
        ["h2", "The mind plans"],
        ["p", "A recipe is a sequence: first gather the ingredients, then mix, then bake. A child who follows a recipe practices planning, working memory and waiting – \"now we wait ten minutes for the oven\". [Illustrated recipes](/parent/recipes) with a picture for every step let even a child who can't read yet follow along alone."],
        ["h2", "Language and math without noticing"],
        ["p", "\"Two spoons\", \"half a cup\", \"one more\", \"more\" and \"less\" – the kitchen is full of quantity and size concepts. Vocabulary grows too: chop, stir, whisk, soft, sticky, crunchy."],
        ["h2", "Meeting new foods"],
        ["p", "Picky eaters taste something they made themselves far more easily. Even just touching, smelling and stirring a new food – without being made to taste it – is progress. Cooking lets children get to know textures and smells at their own pace."],
        ["h2", "What each age can do"],
        ["ul", [
          "Ages 2–3: wash vegetables, pour pre-measured ingredients, stir, sprinkle.",
          "Ages 4–5: spread, cut soft foods with a table knife, crack an egg into a bowl, arrange on a tray.",
          "Ages 6 and up: measure alone, use a peeler, read a simple recipe, cut with close supervision.",
        ]],
        ["tip", "A tip from the clinic: set everything out ahead of time on one tray, and leave your child the parts they can succeed at. The feeling of \"I made it\" is worth more than a perfect recipe."],
        ["p", "And to keep the curiosity going beyond the kitchen, the site's [science experiments for kids](/parent/experiments) use many of the same things you already have in the pantry."],
      ],
    },
  },
  {
    slug: "preparing-an-autistic-child-for-change",
    category: "autism",
    date: "2026-10-13",
    keyword: { he: "הכנת ילד על הרצף לשינוי", en: "preparing an autistic child for change" },
    image: "/icon-bank/navigation-v2/weekly-board-flat.webp",
    links: ["/parent/social-stories", "/parent/weekly-board"],
    he: {
      title: "איך מכינים ילד על הרצף האוטיסטי לשינוי בשגרה",
      description: "שינוי בשגרה יכול להיות קשה מאוד לילד על הרצף. איך מכינים מראש: לוח חזותי, סיפור חברתי, „קודם–אחר כך”, ביקור מקדים ותוכנית להרגעה.",
      body: [
        ["p", "לילדים רבים על הרצף האוטיסטי, השגרה היא עוגן. כשיודעים מה יקרה, העולם צפוי ובטוח יותר. לכן גם שינוי קטן – גננת מחליפה, חג, דרך אחרת לגן – יכול להרגיש גדול מאוד. אי אפשר למנוע כל שינוי, אבל אפשר להכין את הילד כך שהשינוי יפתיע אותו פחות."],
        ["h2", "מספרים מראש, אבל לא מוקדם מדי"],
        ["p", "לכל ילד יש „חלון” משלו. יש ילדים שצריכים לשמוע על שינוי שבוע מראש, ויש כאלה שידאגו כל השבוע ועדיף לספר להם יום לפני. שימו לב מה עובד לילד שלכם, והיצמדו לזה."],
        ["h2", "מראים את השינוי"],
        ["p", "מילים נעלמות, תמונות נשארות. [לוח שבועי](/parent/weekly-board) עם תמונה לכל יום מאפשר לילד לראות מתי השינוי יקרה ומה יבוא אחריו. כשסופרים יחד את הימים עד לשינוי, הוא הופך מדבר מאיים לדבר שאפשר לצפות אליו."],
        ["h2", "סיפור חברתי על השינוי"],
        ["p", "[סיפור חברתי](/parent/social-stories) קצר מתאר מה יקרה, מי יהיה שם, מה הילד עשוי להרגיש ומה הוא יכול לעשות. קוראים אותו כמה ימים לפני, ברגעים רגועים. חשוב לכתוב גם מה נשאר אותו דבר: „גם היום אמא תאסוף אותי בסוף היום”."],
        ["h2", "„קודם – אחר כך”"],
        ["p", "לוח פשוט של שני חלקים – „קודם רופא, אחר כך גן שעשועים” – עוזר לילד לעבור דרך משהו לא מוכר כשהוא יודע שמחכה לו משהו מוכר ואהוב."],
        ["h2", "ביקור מקדים ותמונות"],
        ["p", "אם אפשר, מבקרים במקום החדש לפני – גן חדש, מרפאה, בית של קרובים. אם אי אפשר, מראים תמונות מהמקום ומהאנשים. כל פרט מוכר מקטין את אי הוודאות."],
        ["h2", "מתכננים גם את הרגע הקשה"],
        ["p", "גם עם הכנה טובה, הילד עלול להתקשות. מחליטים מראש מה יעזור: אוזניות, חפץ מרגיע מהבית, מקום שקט לכמה דקות. כשיש תוכנית, גם המבוגר רגוע יותר – והילד מרגיש את זה."],
        ["tip", "טיפ מהקליניקה: הכניסו שינויים קטנים ומתוכננים גם בימים רגילים – דרך אחרת הביתה, כוס בצבע אחר – ובשרו עליהם מראש. תרגול של שינוי קטן בזמן רגוע בונה גמישות לשינויים הגדולים."],
      ],
    },
    en: {
      title: "Preparing an Autistic Child for Change in Routine",
      description: "A change in routine can be very hard for an autistic child. How to prepare: a visual schedule, a social story, first–then, a preview visit and a calming plan.",
      body: [
        ["p", "For many autistic children, routine is an anchor. When they know what will happen, the world is predictable and safer. That is why even a small change – a substitute teacher, a holiday, a different way to school – can feel huge. You can't prevent every change, but you can prepare your child so the change surprises them less."],
        ["h2", "Tell ahead, but not too early"],
        ["p", "Every child has their own \"window\". Some children need to hear about a change a week ahead, while others will worry all week and do better hearing the day before. Notice what works for your child, and stick with it."],
        ["h2", "Show the change"],
        ["p", "Words disappear, pictures stay. A [weekly board](/parent/weekly-board) with a picture for each day lets your child see when the change will happen and what comes after it. Counting down the days together turns the change from something threatening into something to expect."],
        ["h2", "A social story about the change"],
        ["p", "A short [social story](/parent/social-stories) describes what will happen, who will be there, what your child may feel and what they can do. Read it for several days before, at calm moments. Include what stays the same too: \"Today, Mom will still pick me up at the end of the day.\""],
        ["h2", "\"First – then\""],
        ["p", "A simple two-part board – \"first the doctor, then the playground\" – helps a child get through something unfamiliar when they know something familiar and loved is waiting."],
        ["h2", "A preview visit and photos"],
        ["p", "If you can, visit the new place ahead of time – a new school, a clinic, a relative's home. If you can't, show photos of the place and the people. Every familiar detail reduces uncertainty."],
        ["h2", "Plan for the hard moment too"],
        ["p", "Even with good preparation, your child may struggle. Decide in advance what will help: headphones, a comfort object from home, a quiet spot for a few minutes. When there is a plan, the adult is calmer too – and your child feels it."],
        ["tip", "A tip from the clinic: add small, planned changes on ordinary days – a different way home, a different-colored cup – and announce them ahead of time. Practicing a small change at a calm time builds flexibility for the big ones."],
      ],
    },
  },
  {
    slug: "child-who-hates-losing",
    category: "play",
    date: "2026-10-16",
    keyword: { he: "ילד שלא יודע להפסיד", en: "how to help a child who hates losing" },
    image: "/icon-bank/navigation-v2/board-games.webp",
    links: ["/parent/board-games", "/parent/social-stories"],
    he: {
      title: "ילד שלא יודע להפסיד: איך משחקים בלי דמעות",
      description: "למה ילדים מתקשים להפסיד, ומה עוזר: משחקי מזל, משחקים שיתופיים, תרגול הפסד בקטן, מילים לרגש ומבוגר שמדגים איך מפסידים יפה.",
      body: [
        ["p", "הלוח עף, הקלפים מתפזרים, ומישהו בוכה. הפסד במשחק הוא אחד הרגעים הכי מתסכלים לילדים צעירים, וזה טבעי לגמרי: ילדים בגיל הגן עוד לומדים לווסת רגשות חזקים, ולהפסיד זה רגש חזק. החדשות הטובות הן שאפשר ללמד את זה – בדיוק כמו כל מיומנות אחרת."],
        ["h2", "מתחילים ממשחקי מזל"],
        ["p", "במשחק שבו הקובייה מחליטה, קל יותר להפסיד: „לא הפסדתי כי אני לא טוב, פשוט יצא לי מספר קטן”. משחקי מזל פשוטים הם דרך טובה לתרגל ניצחון והפסד בלי שזה ירגיש אישי."],
        ["h2", "משחקים שיתופיים"],
        ["p", "יש משחקים שבהם כולם משחקים יחד נגד המשחק – או שכולם מנצחים או שכולם מפסידים. הם מלמדים לשחק לפי כללים ולחכות לתור, בלי המתח של „מי ניצח”. [במאגר משחקי הקופסה](/parent/board-games) באתר תמצאו משחקים לפי גיל ולפי מה שהם מפתחים."],
        ["h2", "נותנים מילים לרגש"],
        ["p", "„אתה מאוכזב כי רצית לנצח” – כשמבוגר נותן שם לרגש, הילד מרגיש שמבינים אותו, והרגש נעשה פחות מציף. אחר כך אפשר להציע מה עושים עם הרגש: לנשום, להגיד „אוף!”, לבקש עוד משחק."],
        ["h2", "המבוגר מדגים"],
        ["p", "כשאתם מפסידים, אמרו בקול: „אוף, הפסדתי. זה קצת מבאס. אבל היה כיף לשחק. עוד סיבוב?”. ילדים לומדים הרבה יותר ממה שהם רואים מאשר ממה שאומרים להם."],
        ["h2", "לא מוותרים בכוונה כל הזמן"],
        ["p", "מפתה לתת לילד לנצח תמיד כדי להימנע מדמעות, אבל כך הוא לא מתרגל. עדיף לתת לו לנצח חלק מהפעמים, ולהפסיד בחלק – בזמן שיש לו כוח, לא כשהוא עייף או רעב."],
        ["h2", "סיפור חברתי על הפסד"],
        ["p", "ב[מחולל הסיפורים החברתיים](/parent/social-stories) יש סיפור מוכן על מה עושים כשמפסידים במשחק. קוראים אותו יחד לפני שמשחקים, והילד מגיע למשחק עם תוכנית."],
        ["tip", "טיפ מהקליניקה: קבעו יחד „משפט הפסד” קבוע, למשל „הפעם הפסדתי, בפעם הבאה אולי אנצח”. משפט מוכן עוזר לילד לעבור את הרגע בלי להתפרק."],
      ],
    },
    en: {
      title: "How to Help a Child Who Hates Losing",
      description: "Why children find losing so hard, and what helps: games of chance, cooperative games, words for feelings and an adult who shows how to lose well.",
      body: [
        ["p", "The board flies, the cards scatter, and someone is crying. Losing a game is one of the most frustrating moments for young children, and that is completely natural: preschoolers are still learning to handle strong feelings, and losing is a strong feeling. The good news is that it can be taught – just like any other skill."],
        ["h2", "Start with games of chance"],
        ["p", "In a game where the die decides, losing is easier: \"I didn't lose because I'm bad, I just rolled a small number.\" Simple games of chance are a good way to practice winning and losing without it feeling personal."],
        ["h2", "Cooperative games"],
        ["p", "In some games everyone plays together against the game – either everyone wins or everyone loses. They teach playing by the rules and waiting for a turn, without the stress of \"who won\". In the site's [board game guide](/parent/board-games) you'll find games by age and by what they develop."],
        ["h2", "Give the feeling a name"],
        ["p", "\"You're disappointed because you wanted to win\" – when an adult names the feeling, the child feels understood and the feeling becomes less overwhelming. Then you can suggest what to do with it: take a breath, say \"Oh no!\", ask for another round."],
        ["h2", "Show how it's done"],
        ["p", "When you lose, say it out loud: \"Oh, I lost. That's a bit disappointing. But it was fun to play. Another round?\". Children learn much more from what they see than from what they are told."],
        ["h2", "Don't always lose on purpose"],
        ["p", "It's tempting to let your child win every time to avoid tears, but then they never practice. Let them win some games and lose others – when they have the energy, not when they are tired or hungry."],
        ["h2", "A social story about losing"],
        ["p", "The site's [social story builder](/parent/social-stories) has a ready story about what to do when you lose a game. Read it together before playing, so your child comes to the game with a plan."],
        ["tip", "A tip from the clinic: agree on a fixed \"losing sentence\" together, such as \"This time I lost, next time maybe I'll win.\" A ready sentence helps a child get through the moment without falling apart."],
      ],
    },
  },
  {
    slug: "how-to-teach-a-child-to-use-scissors",
    category: "fine-motor",
    date: "2026-10-19",
    keyword: { he: "איך מלמדים ילד לגזור", en: "how to teach a child to cut with scissors" },
    image: "/icon-bank/guidance/scissors/2-thumbs-up.webp",
    links: ["/parent/all"],
    he: {
      title: "איך מלמדים ילד לגזור עם מספריים – שלב אחר שלב",
      description: "איך מלמדים ילד לגזור: אחיזה נכונה עם האגודל למעלה, יד עוזרת, גזירות קטנות, ואז קו ישר, קו מעוגל וצורות. מה מתאים לכל גיל ואילו מספריים לבחור.",
      body: [
        ["p", "גזירה היא אחת המיומנויות המורכבות של הגן: היא דורשת כוח באצבעות, תיאום בין שתי הידיים, התבוננות בקו ותכנון של כל תנועה. לכן היא לומדת בשלבים, ולא בבת אחת. הנה הדרך שבה אני מלמדת אותה בקליניקה."],
        ["h2", "לפני המספריים: ידיים חזקות"],
        ["p", "פתיחה וסגירה של המספריים דומה ללחיצה על אטב או על טפטפת. משחקים כמו [אטבים לפי הצבע](/activity/seed-72) ו[העברת פומפונים עם פינצטה](/activity/seed-37) מכינים את היד לתנועה הזו."],
        ["h2", "שלב 1: אחיזה עם האגודל למעלה"],
        ["p", "האגודל נכנס לחור הקטן, והאצבע האמצעית לחור הגדול, כשהאגודל מצביע לתקרה – „אגודל למעלה, כמו לייק”. כדאי לצייר פרצוף קטן על ציפורן האגודל: אם רואים את הפרצוף, האחיזה נכונה. גם היד השנייה מחזיקה את הדף עם האגודל למעלה."],
        ["h2", "שלב 2: גזירות קטנות"],
        ["p", "מתחילים מ„חתיכות”: רצועות צרות של בריסטול, שנחתכות בגזירה אחת. אחר כך גוזרים שוליים לאורך דף – „דשא” או „שיער”. פעילויות כמו [תספורת לדמות](/activity/seed-70) הופכות את התרגול הזה למשחק."],
        ["h2", "שלב 3: קו ישר"],
        ["p", "מציירים קו עבה על דף קשיח, ומבקשים לגזור לאורכו בפתיחות וסגירות מלאות. היד העוזרת מזיזה את הדף קדימה, והמספריים נשארים ישרים מול הגוף."],
        ["h2", "שלב 4: קווים מעוגלים וצורות"],
        ["p", "אחרי הקו הישר מגיעים קווי זיגזג, קווים מעוגלים, ורק בסוף עיגול וצורות. בגזירת עיגול, היד העוזרת היא שמסובבת את הדף – לא המספריים."],
        ["h2", "איזה מספריים לבחור?"],
        ["ul", [
          "מספריים קטנים לילדים, עם קצה מעוגל, שבאמת חותכים. מספריים שלא חותכים רק מתסכלים.",
          "לילדים שמאליים – מספריים לשמאליים, שבהם הלהבים הפוכים ורואים את הקו.",
          "לילדים שעוד אין להם כוח – מספריים עם קפיץ שנפתחים לבד.",
        ]],
        ["h2", "מה מתאים לכל גיל (בערך)"],
        ["p", "סביב גיל שנתיים וחצי–שלוש ילדים מתחילים לפתוח ולסגור מספריים ולעשות גזירות קטנות. סביב גיל 4 רוב הילדים גוזרים לאורך קו ישר, ובגיל 5–6 גוזרים עיגול וצורות פשוטות. אלה טווחים, לא מבחן – אבל אם בגיל 5 הגזירה עדיין קשה מאוד, כדאי להתייעץ עם מרפאה בעיסוק."],
        ["tip", "טיפ מהקליניקה: ישיבה נכונה משנה הכול. כפות הרגליים על הרצפה, המרפקים קרובים לגוף, והדף בגובה השולחן. כשהגוף יציב, הידיים חופשיות לעבוד."],
      ],
    },
    en: {
      title: "How to Teach a Child to Cut With Scissors, Step by Step",
      description: "How to teach a child to cut: a thumbs-up grip, a helper hand, small snips, then a straight line, curves and shapes. What fits each age and which scissors to choose.",
      body: [
        ["p", "Cutting is one of the most complex preschool skills: it takes finger strength, coordination between both hands, watching the line and planning every movement. That is why it is learned in stages, not all at once. Here is how I teach it in the clinic."],
        ["h2", "Before scissors: strong hands"],
        ["p", "Opening and closing scissors is a lot like squeezing a clothespin or a dropper. Games like [clothespins by color](/activity/seed-72) and [moving pom-poms with tweezers](/activity/seed-37) prepare the hand for this movement."],
        ["h2", "Step 1: A thumbs-up grip"],
        ["p", "The thumb goes in the small hole and the middle finger in the big hole, with the thumb pointing at the ceiling – \"thumbs up!\" Draw a small face on the thumbnail: if you can see the face, the grip is right. The other hand holds the paper with its thumb up too."],
        ["h2", "Step 2: Small snips"],
        ["p", "Start with \"snips\": narrow strips of cardstock that are cut in a single snip. Then fringe along the edge of a page – \"grass\" or \"hair\". Activities like [a haircut for a character](/activity/seed-70) turn this practice into a game."],
        ["h2", "Step 3: A straight line"],
        ["p", "Draw a thick line on stiff paper and ask your child to cut along it with full open-and-close movements. The helper hand moves the paper forward, and the scissors stay straight in front of the body."],
        ["h2", "Step 4: Curves and shapes"],
        ["p", "After the straight line come zigzags and curved lines, and only then circles and shapes. When cutting a circle, the helper hand turns the paper – not the scissors."],
        ["h2", "Which scissors to choose?"],
        ["ul", [
          "Small children's scissors with a rounded tip that really cut. Scissors that don't cut only frustrate.",
          "For left-handed children – left-handed scissors, with reversed blades so the line stays visible.",
          "For children who don't have the strength yet – spring-loaded scissors that open by themselves.",
        ]],
        ["h2", "What fits each age (roughly)"],
        ["p", "Around 2½–3, children start opening and closing scissors and making small snips. Around 4, most children cut along a straight line, and by 5–6 they cut a circle and simple shapes. These are ranges, not a test – but if cutting is still very hard at 5, it's worth talking with an occupational therapist."],
        ["tip", "A tip from the clinic: good sitting changes everything. Feet flat on the floor, elbows close to the body, and the paper at table height. When the body is steady, the hands are free to work."],
      ],
    },
  },
  {
    slug: "how-to-end-screen-time-without-a-fight",
    category: "routine",
    date: "2026-10-22",
    keyword: { he: "איך מסיימים זמן מסך", en: "how to end screen time without a fight" },
    image: "/icon-bank/weekly-board/screen-time.webp",
    links: ["/parent/evening-routine", "/parent/weekly-board"],
    he: {
      title: "איך מסיימים זמן מסך בלי ויכוח",
      description: "למה קשה לילדים לעזוב מסך, ואיך עוזרים: גבול שנקבע מראש, התראה לפני הסוף, טיימר חזותי, סיום בנקודה טבעית ומשהו טוב שמחכה אחרי.",
      body: [
        ["p", "„עוד דקה!”, „רק עד סוף הפרק!” – הרגע שבו צריך לכבות את המסך הוא אחד הרגעים הכי טעונים בבית. זה לא רק עניין של משמעת: מסכים בנויים כך שקשה להפסיק אותם, ולמוח של ילד קשה במיוחד לעבור מפעילות מרגשת לפעילות רגילה. הנה מה שעוזר לעבור את המעבר הזה בשלום."],
        ["h2", "הגבול נקבע לפני שמדליקים"],
        ["p", "הרבה יותר קל להסכים על „שני פרקים” או „עד שהטיימר מצלצל” לפני שהמסך נדלק, מאשר באמצע. כשהגבול ידוע מראש, הסיום הוא לא החלטה שלכם ברגע – אלא הסכם שכבר נעשה."],
        ["h2", "מתריעים לפני הסוף"],
        ["p", "סיום פתאומי מרגיש לילד כמו משהו שנלקח ממנו. התראה של „עוד חמש דקות” ואחר כך „עוד דקה” נותנת לו זמן להתכונן. כדאי לגשת, לגעת בכתף ולוודא שהוא שמע – ילד שמרוכז במסך באמת לא שומע קריאה מהמטבח."],
        ["h2", "טיימר שרואים"],
        ["p", "ילדים צעירים עוד לא מבינים מה זה „חמש דקות”. טיימר חזותי, שבו רואים את הזמן מתכווץ, הופך את הזמן למשהו מוחשי. כשהטיימר מצלצל, הוא „מחליט” – לא אתם."],
        ["h2", "מסיימים בנקודה טבעית"],
        ["p", "לעצור באמצע שלב במשחק או באמצע סצנה זה מתסכל במיוחד. עדיף לסיים בסוף פרק או בסוף שלב, גם אם זה אומר עוד שתי דקות."],
        ["h2", "משהו טוב מחכה אחרי"],
        ["p", "המעבר קל יותר כשיודעים מה בא אחר כך, ובמיוחד אם זה משהו נעים: ארוחה, אמבטיה עם צעצועים, סיפור. [לוח התארגנות ערב](/parent/evening-routine) שבו המסך הוא שלב אחד מתוך הרצף – ואחריו תמונה של מה שבא – עוזר לילד לראות שהערב ממשיך. ב[לוח השבועי](/parent/weekly-board) אפשר גם לסמן באילו ימים יש זמן מסך."],
        ["h2", "ואם בכל זאת יש התפרצות"],
        ["p", "נשארים רגועים, מכירים ברגש („קשה לך להפסיק, היה כיף”), ולא נכנעים ברגע הזה. אם תמיד מוסיפים עוד דקה אחרי צעקות, הילד לומד שצעקות עובדות. אחרי שכולם נרגעו, אפשר לדבר על איך לעשות את זה אחרת מחר."],
        ["tip", "טיפ מהקליניקה: אחרי מסך, הגוף צריך „לחזור”. תנועה קצרה – קפיצות, סחיבת כביסה, מלחמת כריות – עוזרת לילדים רבים לעבור ממצב של ישיבה מרוכזת לפעילות הבאה."],
      ],
    },
    en: {
      title: "How to End Screen Time Without a Fight",
      description: "Why kids find it hard to leave a screen, and what helps: a limit set in advance, a warning, a visual timer and something good waiting after.",
      body: [
        ["p", "\"One more minute!\", \"Just until the end of the episode!\" – the moment the screen has to go off is one of the most loaded moments at home. It isn't only about discipline: screens are designed to be hard to stop, and a child's brain finds it especially hard to switch from something exciting to something ordinary. Here is what helps get through this transition in peace."],
        ["h2", "Set the limit before it goes on"],
        ["p", "It is much easier to agree on \"two episodes\" or \"until the timer rings\" before the screen goes on than in the middle. When the limit is known in advance, the ending isn't your decision in the moment – it's an agreement already made."],
        ["h2", "Warn before the end"],
        ["p", "A sudden ending feels to a child like something being taken away. A \"five more minutes\" warning and then \"one more minute\" gives them time to get ready. Walk over, touch their shoulder and make sure they heard – a child absorbed in a screen really doesn't hear a call from the kitchen."],
        ["h2", "A timer they can see"],
        ["p", "Young children don't yet understand what \"five minutes\" means. A visual timer, where you can see the time shrinking, makes time concrete. When the timer rings, it \"decides\" – not you."],
        ["h2", "Stop at a natural point"],
        ["p", "Stopping in the middle of a game level or a scene is especially frustrating. It is better to stop at the end of an episode or a level, even if that means two more minutes."],
        ["h2", "Something good comes next"],
        ["p", "The switch is easier when your child knows what comes next, especially if it's something pleasant: dinner, a bath with toys, a story. An [evening routine board](/parent/evening-routine) where the screen is one step in the sequence – followed by a picture of what comes next – helps your child see that the evening goes on. On the [weekly board](/parent/weekly-board) you can also mark which days have screen time."],
        ["h2", "And if there's a meltdown anyway"],
        ["p", "Stay calm, acknowledge the feeling (\"It's hard to stop, it was fun\"), and don't give in at that moment. If a minute is always added after yelling, your child learns that yelling works. Once everyone has calmed down, talk about how to do it differently tomorrow."],
        ["tip", "A tip from the clinic: after a screen, the body needs to \"come back\". A short burst of movement – jumping, carrying laundry, a pillow fight – helps many children shift from focused sitting to the next activity."],
      ],
    },
  },
  {
    slug: "child-sensitive-to-noise",
    category: "sensory",
    date: "2026-10-25",
    keyword: { he: "ילד רגיש לרעשים", en: "child sensitive to noise" },
    image: "/icon-bank/search/noise-sensitivity.webp",
    links: ["/parent/all", "/parent/social-stories"],
    he: {
      title: "ילד רגיש לרעשים: מה עוזר בבית ובגן",
      description: "ילד שמכסה אוזניים, בורח מיום הולדת או נבהל משואב אבק: למה זה קורה, איך עוזרים בבית ובגן, מתי אוזניות מתאימות ומתי כדאי לפנות להערכה.",
      body: [
        ["p", "יש ילדים שמכסים את האוזניים כשמפעילים את הבלנדר, בורחים מחגיגת יום הולדת או נבהלים כל פעם מחדש משואב האבק. לפעמים מבוגרים חושבים שהם „מגזימים”, אבל עבור ילד עם רגישות שמיעתית הרעש באמת מרגיש חזק, פתאומי ולא נעים – הרבה יותר ממה שאנחנו שומעים."],
        ["h2", "למה זה קורה?"],
        ["p", "המוח שלנו מסנן כל הזמן צלילים: הוא מחליט מה חשוב לשמוע ומה אפשר להתעלם ממנו. אצל חלק מהילדים הסינון הזה עובד אחרת, וצלילים שאחרים בקושי שמים לב אליהם – זמזום של מקרר, רעש של ילדים בגן – מגיעים חזק ומעייפים. רגישות לרעשים שכיחה יותר אצל ילדים עם קשיי ויסות חושי ואצל ילדים על הרצף, אבל היא מופיעה גם אצל ילדים בלי שום אבחנה."],
        ["h2", "מה עוזר בבית"],
        ["ul", [
          "מזהירים לפני רעש: „עכשיו אני מדליקה את הבלנדר”. רעש צפוי מפחיד הרבה פחות מרעש פתאומי.",
          "נותנים לילד שליטה: לתת לו ללחוץ בעצמו על הכפתור של השואב, או לבחור לצאת מהחדר.",
          "מקום שקט: פינה או חדר שאפשר ללכת אליהם כשיש יותר מדי רעש.",
          "משחקי האזנה ברגעים רגועים – כמו [מאיפה הרעש?](/activity/seed-104) – עוזרים לילד להתייחס לצלילים כמשהו מעניין ולא רק מאיים.",
        ]],
        ["h2", "מה עוזר בגן ובאירועים"],
        ["p", "מספרים לצוות הגן על הרגישות ומבקשים מקום שקט יותר לארוחה או למנוחה. לפני אירוע רועש – יום הולדת, מסיבת חנוכה – מכינים את הילד: מה יהיה שם, כמה זמן, ומה עושים אם זה יותר מדי. [סיפור חברתי](/parent/social-stories) קצר על האירוע עוזר מאוד."],
        ["h2", "ומה עם אוזניות?"],
        ["p", "אוזניות שמפחיתות רעש הן כלי מצוין לאירועים רועשים, לנסיעות ולמקומות הומים. עם זאת, לא כדאי שהילד ירכיב אותן כל היום, כי המטרה היא גם לעזור לו להתרגל בהדרגה לרעשים של היום־יום. משתמשים בהן כשצריך, ומורידים כשהסביבה רגועה."],
        ["h2", "מתי לפנות להערכה"],
        ["p", "אם הרגישות מונעת מהילד להשתתף בגן, בחוגים או באירועים משפחתיים, אם היא מלווה בהתפרצויות קשות, או אם יש רגישות גם לגירויים אחרים – מגע, בגדים, אוכל – כדאי לפנות למרפאה בעיסוק להערכה של ויסות חושי. וחשוב לבדוק גם את השמיעה עצמה, כדי לשלול בעיה רפואית."],
        ["tip", "טיפ מהקליניקה: לחץ עמוק מרגיע את מערכת העצבים. חיבוק חזק, עטיפה בשמיכה כמו „בוריטו” או לחיצות על הכתפיים יכולים לעזור לילד להירגע אחרי רעש שהציף אותו."],
      ],
    },
    en: {
      title: "A Child Sensitive to Noise: What Helps at Home and at School",
      description: "A child who covers their ears or panics at the vacuum: why it happens, what helps at home and at school, when to use headphones and when to get an evaluation.",
      body: [
        ["p", "Some children cover their ears when the blender goes on, run away from birthday parties, or get scared every single time the vacuum starts. Adults sometimes think they are \"overreacting\", but for a child with sound sensitivity, the noise really does feel loud, sudden and unpleasant – much more than what we hear."],
        ["h2", "Why does it happen?"],
        ["p", "Our brain constantly filters sounds: it decides what is important to hear and what can be ignored. In some children this filtering works differently, and sounds others barely notice – a humming fridge, a noisy classroom – come through loud and tiring. Noise sensitivity is more common in children with sensory processing difficulties and in autistic children, but it also appears in children with no diagnosis at all."],
        ["h2", "What helps at home"],
        ["ul", [
          "Warn before a noise: \"I'm turning on the blender now.\" An expected noise is far less scary than a sudden one.",
          "Give your child control: let them press the vacuum's button themselves, or choose to leave the room.",
          "A quiet place: a corner or room they can go to when there is too much noise.",
          "Listening games at calm times – like [Where's that sound?](/activity/seed-104) – help a child treat sounds as something interesting, not only threatening.",
        ]],
        ["h2", "What helps at school and events"],
        ["p", "Tell the preschool or school staff about the sensitivity and ask for a quieter spot for meals or rest. Before a noisy event – a birthday, a holiday party – prepare your child: what will be there, for how long, and what to do if it's too much. A short [social story](/parent/social-stories) about the event helps a lot."],
        ["h2", "What about headphones?"],
        ["p", "Noise-reducing headphones are a great tool for noisy events, trips and crowded places. Still, it's better not to wear them all day, because part of the goal is to help your child gradually get used to everyday sounds. Use them when needed, and take them off when the surroundings are calm."],
        ["h2", "When to ask for an evaluation"],
        ["p", "If the sensitivity keeps your child from joining in at school, after-school activities or family events, if it comes with severe meltdowns, or if there is sensitivity to other input too – touch, clothes, food – ask an occupational therapist for a sensory processing evaluation. It's also important to check hearing itself, to rule out a medical issue."],
        ["tip", "A tip from the clinic: deep pressure calms the nervous system. A firm hug, wrapping up in a blanket like a \"burrito\" or pressing down on the shoulders can help a child settle after a noise that overwhelmed them."],
      ],
    },
  },
];
