// Small copies of the pictures shown on activity cards (search grids, all activities, home), so a
// grid of cards does not download dozens of full-size illustrations.
//   CHROME_PATH=/path/to/chrome node scripts/make-thumbs.mjs
// Writes public/icon-bank/thumbs/<same path> (at most 480px, WebP) for every card picture over 30 KB,
// and src/lib/thumb-list.js with the pictures that have a thumbnail. Run it after adding illustrations;
// a picture without a thumbnail simply keeps using the original.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import puppeteer from "puppeteer-core";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pub = path.join(root, "public");
const MAX = 480;
const MIN_BYTES = 30 * 1024;

function sources() {
  const found = new Set();
  const walk = (dir) => fs.readdirSync(dir, { withFileTypes: true }).forEach((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return walk(full);
    if (!/\.(jsx?|json)$/.test(entry.name)) return;
    const text = fs.readFileSync(full, "utf8");
    for (const match of text.matchAll(/\b"?(?:cover|hero|hero_image|image)"?\s*:\s*"(\/icon-bank\/[^"]+\.(?:webp|png|jpg))"/g)) found.add(match[1]);
    for (const match of text.matchAll(/"(\/icon-bank\/[^"]*(?:hero|cover)[^"]*\.(?:webp|png|jpg))"/gi)) found.add(match[1]);
  });
  walk(path.join(root, "src"));
  // Card pictures whose paths are put together in code: experiment heroes, story covers, board games.
  const byName = (dir, test) => {
    const base = path.join(pub, "icon-bank", dir);
    if (!fs.existsSync(base)) return;
    const visit = (folder) => fs.readdirSync(folder, { withFileTypes: true }).forEach((entry) => {
      const full = path.join(folder, entry.name);
      if (entry.isDirectory()) return visit(full);
      if (/\.(webp|png|jpg)$/.test(entry.name) && test(entry.name)) found.add(`/${path.relative(pub, full).split(path.sep).join("/")}`);
    });
    visit(base);
  };
  byName("manual/experiments", (name) => name.includes("hero"));
  byName("social-stories", (name) => name.includes("cover") || name === "toilet.webp");
  byName("board-games", () => true);
  const activities = path.join(pub, "icon-bank/activities");
  if (fs.existsSync(activities)) fs.readdirSync(activities).filter((name) => name.endsWith(".webp")).forEach((name) => found.add(`/icon-bank/activities/${name}`));
  return [...found].filter((src) => !src.startsWith("/icon-bank/thumbs/") && fs.existsSync(path.join(pub, src)) && fs.statSync(path.join(pub, src)).size > MIN_BYTES).sort();
}

const list = sources();
const browser = await puppeteer.launch({ executablePath: process.env.CHROME_PATH, args: ["--no-sandbox"] });
const page = await browser.newPage();
let made = 0;
for (const src of list) {
  const input = path.join(pub, src);
  const output = path.join(pub, "icon-bank/thumbs", src.replace(/^\/icon-bank\//, "")).replace(/\.(png|jpg)$/, ".webp");
  if (fs.existsSync(output) && fs.statSync(output).mtimeMs >= fs.statSync(input).mtimeMs) continue;
  const type = src.endsWith(".png") ? "image/png" : src.endsWith(".jpg") ? "image/jpeg" : "image/webp";
  const dataUrl = await page.evaluate(async (data, type, max) => {
    const img = new Image();
    img.src = `data:${type};base64,${data}`;
    await img.decode();
    const scale = Math.min(1, max / Math.max(img.width, img.height));
    const canvas = document.createElement("canvas");
    canvas.width = Math.round(img.width * scale);
    canvas.height = Math.round(img.height * scale);
    const ctx = canvas.getContext("2d");
    ctx.imageSmoothingQuality = "high";
    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
    return canvas.toDataURL("image/webp", 0.82);
  }, fs.readFileSync(input).toString("base64"), type, MAX);
  fs.mkdirSync(path.dirname(output), { recursive: true });
  fs.writeFileSync(output, Buffer.from(dataUrl.split(",")[1], "base64"));
  made += 1;
}
await browser.close();

const withThumb = list.filter((src) => fs.existsSync(path.join(pub, "icon-bank/thumbs", src.replace(/^\/icon-bank\//, "")).replace(/\.(png|jpg)$/, ".webp")));
fs.writeFileSync(path.join(root, "src/lib/thumb-list.js"), `// Generated by scripts/make-thumbs.mjs: card pictures that have a small copy under /icon-bank/thumbs/.\nexport const THUMB_SOURCES = new Set(${JSON.stringify(withThumb, null, 2)});\n`);
console.log(`${list.length} card pictures, ${made} thumbnails made, ${withThumb.length} listed`);
